routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use \App\Http\Controllers\Admin\Auth\LoginController as AdminLoginController;
use \App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //  Getting banner list
    $banners    =   \App\Models\Banner::where('is_active',1)->get();

    return view('welcome',compact(['banners']));
})->name('homepage');

Route::get('/about-us', function () {
    return view('about-us');
})->name('about-us');

Route::prefix('services/')->as('services.')->group(function () {
   
    Route::get('freight-forwarding', function () {
        return view('services.freight-forwarding');
    })->name('freight.forwarding');
    
    Route::get('ocean-freight', function () {
        return view('services.ocean-freight');
    })->name('freight.ocean');
    
    Route::get('air-freight', function () {
        return view('services.air-freight');
    })->name('freight.air');
    
    Route::get('trucking-freight', function () {
        return view('services.trucking-freight');
    })->name('freight.trucking');
    
    Route::get('warehouse-and-distribution', function () {
        return view('services.warehouse-distribution');
    })->name('warehouse.distribution');

});

// Route::get('/blogs', function () {
//     return view('blogs');
// })->name('blogs');

Route::get('/blogs/{slug?}',[HomeController::class,'blogDetails'])->name('blogs.details');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//  Route to track order details
Route::get('order/tracking/details',[HomeController::class,'index'])->name('order.tracking.details');

//  Route to save contact query by user
Route::post('contact/query',[HomeController::class,'saveContactQuery'])->name('contact.query.save');

/*----------------------------------------------
 *  ADMIN Routes
 * ---------------------------------------------
 * */

Route::prefix('admin/')->as('admin.')->group(function(){

    Route::get('/',function(){
        return redirect()->route('admin.login.show');
    });

    //  Login Route
    Route::get('login',[AdminLoginController::class,'create'])->name('login.show');
    
    //  Login Post Route
    Route::post('login',[AdminLoginController::class,'store'])->name('login');
    
    //  Forgot Password Form Route
    Route::get('forgot/password',[ForgotPasswordController::class,'forgotPasswordForm'])->name('forgot.password');
    
    //  Forgot Password Form Submit and reset password link Route
    Route::post('forgot/password',[ForgotPasswordController::class,'sendResetPasswordLink'])->name('forgot.password.submit');
    
    //  Reset Password form Route
    Route::get('reset/password/{token}',[ResetPasswordController::class,'resetPasswordForm'])->name('reset.password.form');
    
    //  Reset Password form submit Route
    Route::post('reset/password',[ResetPasswordController::class,'resetPassword'])->name('reset.password.form.submit');

    /*--------------------------------------------------
     *  ADMIN Auth Routes
     *--------------------------------------------------
     */
    Route::middleware('auth')->group(function(){

        //  Logout Route
        Route::post('logout',[AdminLoginController::class,'destroy'])->name('logout');

        //  Dashboard Route
        Route::get('dashboard',[AdminController::class,'dashboard'])->name('dashboard');
        
        //  Update Password Form Route
        Route::get('update/password',[AdminController::class,'changePasswordForm'])->name('update.password.form');
        
        //  Update Password Form Submit Route
        Route::post('update/password',[AdminController::class,'submitChangePasswordForm'])->name('update.password.form.submit');

        //  Order Routes Group
        Route::prefix('order/')->as('order.')->group(function(){

            //  Order List
            Route::get('list/{type}',[AdminController::class,'orderList'])->name('list');
            
            //  Create Order
            Route::post('data',[AdminController::class,'createOrder'])->name('create');
            
            //  Import Order Data
            Route::post('data/import',[AdminController::class,'importOrderData'])->name('import.data');

            //  Order Status Data
            Route::get('status/data/{order_id}',[AdminController::class,'orderStatusData'])->name('status.data');

            //  Order Data to Edit
            Route::get('edit/{order_id}',[AdminController::class,'editOrderData'])->name('edit');
            
            //  Update Order Data
            Route::put('update/{order_id}',[AdminController::class,'updateOrderData'])->name('update');

            //  Update Order Status
            Route::put('status/update/{order_id}',[AdminController::class,'updateOrderStatus'])->name('update.status');

        });

        //  Banner List route
       //  Route::get('banners/list',[AdminController::class,'bannerList'])->name('banners.list');
        
        //  Add Banner route
        // Route::post('banners/add',[AdminController::class,'addBanner'])->name('banners.add');
        
        //  Delete Banner route
        // Route::delete('banners/delete/{banner_id}',[AdminController::class,'destroyBanner'])->name('banners.destroy');
        
        //  Contact Queries route
        Route::get('contact/queries',[AdminController::class,'contactQueries'])->name('contact.queries');
        
        //  Contact Query Admin Response route
        Route::post('contact/queries/response',[AdminController::class,'contactQueryResponse'])->name('contact.query.response');
        
        //  Resource route of Sub Admin
        Route::resource('sub/admin', SubAdminController::class)->names('sub.admin')->parameters([
            'admin' =>  'id'
        ]);
        
        //  Resource route of Sub Admin
        Route::resource('blogs', BlogController::class)->names('blogs')->parameters([
             'blog' =>  'id'
        ]);
        
        //  Activate, Deactivate, Delete Sub Admin route
        Route::get('sub/admin/activate/deactivate/delete/{action}/{data_id}',[AdminController::class,'activateDeactivateDeleteSubAdmin'])->name('sub.admin.activate.deactivate.delete');

        //  Custom Email Notification Form
        // Route::get('custom/email/notification',[AdminController::class,'customEmailNotificationForm'])->name('custom.email.notification');
        Route::get('custom/email/notification',function(){
            return view('admin.custom-email-notification');
        })->name('custom.email.notification');
        
        //  Custom Email Notification Form Submit
        Route::post('custom/email/notification',[AdminController::class,'sendCustomEmailNotification'])->name('send.custom.email.notification');
    });
});

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/about-us.blade.php
@extends('layouts.website.main')
@section('title','About Us')
@section('content')
<!--  start  about  -->
<div class="banner-inner-page" style="background: url(assets/images/about_banner.png);">
	<div class="container">
		<div class="row">
			
		</div>
	</div>
</div>
<!--  end  about  -->

<div class="about-page-block">
	<div class="container">
		<div class="row">
			<div class="text">
				<h2>About TPCL</h2>
				<p><b>TRANSPACIFIC CARGO AND LOGISTICS</b> mission is to facilitate our clients’ growth and development by providing efficient and effective supply chain partnerships with an emphasis on quality, performance, and integrity. Our headquarters in Los Angeles, California positions us next to the largest port in the United States. We have branch offices in Chicago, Illinois, Miami, Florida, Charleston, South Carolina and Mexico, Bogota, Colombia.</p>
				<p>Our vision is to establish a culture of equity, opportunity, and growth amongst all stakeholders, where open and honest communication guides the development of individuals and partnerships, allowing them to reach their full potential. To expand our global footprint through our mission of uncompromising quality, performance, and integrity, increasing our scope and capabilities while remaining dedicated to our corporate values.</p>
				<p>Through an emphasis on customer service to our clients as well as our valued worldwide partners, we have been rewarded with extensive support and growth.</p>
				<p>It is our dedicated and custom-built service that separates us from our competitors.</p>
				<p>We value a sense of urgency and impeccable execution in the services we provide.</p>
				<p>We encourage a “Speak Up, Listen, and Take Action” culture amongst our teams, and embody a “No Excuses” mentality toward success.</p>
			</div>
		</div>
	</div>
</div>


<!--  branches start  -->
<div class="about-our-services">
	<div class="container">
		<div class="row heading">
			<h2>Our services</h2>
		</div>
		
		<div class="row about-services">
			<div class="col-md-4 item-single">
				<a href="{{ route('services.freight.forwarding') }}">
					<div class="item">
						<div class="image">
							<img src="{{ asset('assets/images/freight.png') }}"/>
							<h2>FREIGHT FORWARDING</h2>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-4 item-single">
				<a href="{{ route('services.freight.ocean') }}">
					<div class="item">
						<div class="image">
							<img src="{{ asset('assets/images/ocean-freight.png') }}"/>
							<h2>OCEAN FREIGHT</h2>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-4 item-single">
				<a href="{{ route('services.freight.air') }}">
					<div class="item">
						<div class="image">
							<img src="{{ asset('assets/images/air-freight.png') }}"/>
							<h2>AIR FREIGHT</h2>
						</div>
					</div>
				</a>
			</div>
		</div>
		
		<div class="row about-services">
			<div class="col-md-4 item-single">
				<a href="{{ route('services.freight.trucking') }}">
					<div class="item">
						<div class="image">
							<img src="{{ asset('assets/images/trucking.png') }}"/>
							<h2>TRUCKING FREIGHT SERVICES</h2>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-4 item-single">
				<a href="{{ route('services.warehouse.distribution') }}">
					<div class="item">
						<div class="image">
							<img src="{{ asset('assets/images/warehouse.png') }}"/>
							<h2>WAREHOUSE AND DISTRIBUTION</h2>
						</div>
					</div>
				</a>
			</div>
		</div>
		
	</div>
</div>
<!--  branches end  -->
@endsection

resources/views/blogs.blade.php
@extends('layouts.website.main')
@section('title','Blogs')
@section('content')
<!--  home section serve start  -->
<div class="blog-page-box">
	<div class="container">
		<div class="row">
			<div class="col-md-8 blog-left">
				<div class="blog-text">
					<div class="blog-image">
						<img src="{{ $blogDetails->image }}"/>
					</div>
					<h2>{{ $blogDetails->title }}</h2>
					<p>{!! $blogDetails->content !!}</p>
				</div>
			</div>
			<div class="col-md-4 blog-right">
				<div class="recent-post">
					<h2>Recent Posts</h2>
					<ul>
						@foreach ($recentBlogs as $recentBlog)
							<li>
								<a href="{{ route('blogs.details',['slug'=>$recentBlog->slug]) }}">{{ $recentBlog->title }}</a>
							</li>
						@endforeach
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!--  home section serve end  -->
@endsection

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    You're logged in!
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/order_tracking_details.blade.php
<div class="modal-dialog" style="max-width: 80%;">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title">Order Tracking Details</h4>
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body">
            <div class="col-12">
                <div class="row">
                    <div class="col-4">
                        <h5 for="">Tracking Number :</h5>
                        <span><b>{{ $orderData->item_tracking_number }}</b></span>
                    </div>
                    <div class="col-4">
                        <h5 for="">Order Date :</h5>
                        <span><b>{{ date('d M Y H:i:s A', strtotime($orderData->created_at)) }}</b></span>
                    </div>
                    <div class="col-4">
                        <h5 for="">Shipping Address :</h5>
                        <span><b>{{ $orderData->shipping_address }}</b></span>
                    </div>
                </div>
                <br>
                <div class="row">
                    <div class="col-4">
                        <h5 for="">Item Name :</h5>
                        <span><b>{{ $orderData->item_name }}</b></span>
                    </div>
                    <div class="col-4">
                        <h5 for="">Item Weight :</h5>
                        <span><b>{{ $orderData->item_weight }}</b></span>
                    </div>
                    <div class="col-4">
                        <h5 for="">Package Details :</h5>
                        <span><b>{{ $orderData->address_from }}</b></span>
                    </div>
                </div>
                <!-- <br> -->
                <hr>
                <div class="row">
                    
                    <table class="table table-striped table-bordered table-hover dataTables-example" id="order-status-tracking-datatable">
                        <thead>
                            <tr>
                                <th>Sr. No.</th>
                                <th>Order Status</th>
                                <th>Date & Time</th>
                                <th>Comment</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($orderData->order_status as $key => $status)
                                <tr style="background-color: {{ $status->color }};">
                                    <td>
                                        {{ $key+1 }}
                                    </td>
                                    <td>
                                        <b>{{ strtoupper($status->order_status) }}</b>
                                    </td>
                                    <td>
                                        {{ date('d M Y H:i:s A',strtotime($status->created_at)) }}
                                    </td>
                                    <td>
                                        {{ $status->comment }}
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <hr>
            <div class="col-12">
                <div class="row">
                    <table class="table table-bordered">
                        
                    </table>
                </div>
            </div>
        </div>
        <div class="modal-footer">

        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
		$('.dataTables-example').DataTable({
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                // buttons: [
                //     {extend: 'copy'},
                //     {extend: 'csv'},
                //     {extend: 'excel', title: 'ExampleFile'},
                //     {extend: 'pdf', title: 'ExampleFile'},

                //     // {extend: 'print',
                //     //  customize: function (win){
                //     //         $(win.document.body).addClass('white-bg');
                //     //         $(win.document.body).css('font-size', '10px');

                //     //         $(win.document.body).find('table')
                //     //                 .addClass('compact')
                //     //                 .css('font-size', 'inherit');
                //     // }
                //     // }
                // ]

            });
	});
</script>