routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use \App\Http\Controllers\Admin\Auth\LoginController as AdminLoginController;
use \App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //  Getting banner list
    $banners    =   \App\Models\Banner::where('is_active',1)->get();

    return view('welcome',compact(['banners']));
})->name('homepage');

Route::get('/about-us', function () {
    return view('about-us');
})->name('about-us');

Route::prefix('services/')->as('services.')->group(function () {
   
    Route::get('freight-forwarding', function () {
        return view('services.freight-forwarding');
    })->name('freight.forwarding');
    
    Route::get('ocean-freight', function () {
        return view('services.ocean-freight');
    })->name('freight.ocean');
    
    Route::get('air-freight', function () {
        return view('services.air-freight');
    })->name('freight.air');
    
    Route::get('trucking-freight', function () {
        return view('services.trucking-freight');
    })->name('freight.trucking');
    
    Route::get('warehouse-and-distribution', function () {
        return view('services.warehouse-distribution');
    })->name('warehouse.distribution');

});

// Route::get('/blogs', function () {
//     return view('blogs');
// })->name('blogs');

Route::get('/blogs/{slug?}',[HomeController::class,'blogDetails'])->name('blogs.details');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//  Route to track order details
Route::get('order/tracking/details',[HomeController::class,'index'])->name('order.tracking.details');

//  Route to save contact query by user
Route::post('contact/query',[HomeController::class,'saveContactQuery'])->name('contact.query.save');

/*----------------------------------------------
 *  ADMIN Routes
 * ---------------------------------------------
 * */

Route::prefix('admin/')->as('admin.')->group(function(){

    Route::get('/',function(){
        return redirect()->route('admin.login.show');
    });

    //  Login Route
    Route::get('login',[AdminLoginController::class,'create'])->name('login.show');
    
    //  Login Post Route
    Route::post('login',[AdminLoginController::class,'store'])->name('login');
    
    //  Forgot Password Form Route
    Route::get('forgot/password',[ForgotPasswordController::class,'forgotPasswordForm'])->name('forgot.password');
    
    //  Forgot Password Form Submit and reset password link Route
    Route::post('forgot/password',[ForgotPasswordController::class,'sendResetPasswordLink'])->name('forgot.password.submit');
    
    //  Reset Password form Route
    Route::get('reset/password/{token}',[ResetPasswordController::class,'resetPasswordForm'])->name('reset.password.form');
    
    //  Reset Password form submit Route
    Route::post('reset/password',[ResetPasswordController::class,'resetPassword'])->name('reset.password.form.submit');

    /*--------------------------------------------------
     *  ADMIN Auth Routes
     *--------------------------------------------------
     */
    Route::middleware('auth')->group(function(){

        //  Logout Route
        Route::post('logout',[AdminLoginController::class,'destroy'])->name('logout');

        //  Dashboard Route
        Route::get('dashboard',[AdminController::class,'dashboard'])->name('dashboard');
        
        //  Update Password Form Route
        Route::get('update/password',[AdminController::class,'changePasswordForm'])->name('update.password.form');
        
        //  Update Password Form Submit Route
        Route::post('update/password',[AdminController::class,'submitChangePasswordForm'])->name('update.password.form.submit');

        //  Order Routes Group
        Route::prefix('order/')->as('order.')->group(function(){

            //  Order List
            Route::get('list/{type}',[AdminController::class,'orderList'])->name('list');
            
            //  Create Order
            Route::post('data',[AdminController::class,'createOrder'])->name('create');
            
            //  Import Order Data
            Route::post('data/import',[AdminController::class,'importOrderData'])->name('import.data');

            //  Order Status Data
            Route::get('status/data/{order_id}',[AdminController::class,'orderStatusData'])->name('status.data');

            //  Order Data to Edit
            Route::get('edit/{order_id}',[AdminController::class,'editOrderData'])->name('edit');
            
            //  Update Order Data
            Route::put('update/{order_id}',[AdminController::class,'updateOrderData'])->name('update');

            //  Update Order Status
            Route::put('status/update/{order_id}',[AdminController::class,'updateOrderStatus'])->name('update.status');

        });

        //  Banner List route
       //  Route::get('banners/list',[AdminController::class,'bannerList'])->name('banners.list');
        
        //  Add Banner route
        // Route::post('banners/add',[AdminController::class,'addBanner'])->name('banners.add');
        
        //  Delete Banner route
        // Route::delete('banners/delete/{banner_id}',[AdminController::class,'destroyBanner'])->name('banners.destroy');
        
        //  Contact Queries route
        Route::get('contact/queries',[AdminController::class,'contactQueries'])->name('contact.queries');
        
        //  Contact Query Admin Response route
        Route::post('contact/queries/response',[AdminController::class,'contactQueryResponse'])->name('contact.query.response');
        
        //  Resource route of Sub Admin
        Route::resource('sub/admin', SubAdminController::class)->names('sub.admin')->parameters([
            'admin' =>  'id'
        ]);
        
        //  Resource route of Sub Admin
        Route::resource('blogs', BlogController::class)->names('blogs')->parameters([
             'blog' =>  'id'
        ]);
        
        //  Activate, Deactivate, Delete Sub Admin route
        Route::get('sub/admin/activate/deactivate/delete/{action}/{data_id}',[AdminController::class,'activateDeactivateDeleteSubAdmin'])->name('sub.admin.activate.deactivate.delete');

        //  Custom Email Notification Form
        // Route::get('custom/email/notification',[AdminController::class,'customEmailNotificationForm'])->name('custom.email.notification');
        Route::get('custom/email/notification',function(){
            return view('admin.custom-email-notification');
        })->name('custom.email.notification');
        
        //  Custom Email Notification Form Submit
        Route::post('custom/email/notification',[AdminController::class,'sendCustomEmailNotification'])->name('send.custom.email.notification');
    });
});

resources/views/admin/404-not-found.blade.php
@extends('layouts.admin.main')
@section('title','404 Not Found')
@section('content')
<div class="middle-box text-center animated fadeInDown">
    <h1>404</h1>
    <h3 class="font-bold">Page Not Found</h3>

    <div class="error-desc">
        Sorry, but the page you are looking for has note been found. Try checking the URL for error, then hit the refresh button on your browser or try found something else in our app.
        <!-- <form class="form-inline m-t" role="form">
            <div class="form-group">
                <input type="text" class="form-control" placeholder="Search for page">
            </div>
            <button type="submit" class="btn btn-primary">Search</button>
        </form> -->
    </div>
</div>
@endsection

resources/views/admin/contact-queries.blade.php
@extends('layouts.admin.main')
@section('title','Contact Queries')
@section('content')
<link href="{{ asset('admin_assets/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Contact Query List</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Contact Queries</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Contact Query list with data</h5>
                    <!-- <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#" class="dropdown-item">Config option 1</a>
                            </li>
                            <li><a href="#" class="dropdown-item">Config option 2</a>
                            </li>
                        </ul>
                        <button type="button" href="javascript:void()" data-target="#add-order-data-modal" data-toggle="modal" class="btn btn-w-m btn-primary" style="margin-top: -7px;">
                            Add Order
                        </button>
                    </div> -->
                </div>
                <div class="ibox-content">

                    <div class="table-responsive">
                <table class="table table-striped table-bordered table-hover dataTables-example" >
                <thead>
                <tr>
                    <th>Sr. No.</th>
                    <th>Name </th>
                    <th>Email</th>
                    <th>Query</th>
                    <th>Query Date/Time</th>
                    <th>Responded</th>
                    <th>Action</th>
                </tr>
                </thead>
                <tbody>
                    @foreach ($contact_queries as $key => $query)
                        <tr class="gradeX">
                            <td>
                                {{ $key+1 }}
                            </td>
                            <td>
                                {{ $query->name }}
                            </td>
                            <td>
                                {{ $query->email }}
                            </td>
                            <td>
                                {{ $query->query }}
                            </td>
                            <td>
                                {{ date('d M Y H:i',strtotime($query->created_at)) }}
                            </td>
                            <td>
                                @if ($query->admin_responded)
                                    <span class="badge badge-success">Responded</span>
                                @else
                                    <span class="badge badge-warning">Pending</span>
                                    
                                @endif
                            </td>
                            <td>

                                <a href="javascript:void(0)" onclick="showQueryDataModal('{{ $query->query }}','{{ encrypt($query->id) }}','{{$query->admin_response}}')">
                                    <i class="fa fa-eye"></i>
                                </a>
                                &nbsp;|&nbsp;
                                <a href="javascript:void(0)" onclick="showContactQueryReplyFormModal('{{ encrypt($query->id) }}')">
                                    <i class="fa fa-mail-reply"></i>
                                </a>
                                <!-- &nbsp;|&nbsp;
                                <a href="javascript:void()">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                &nbsp;|&nbsp; -->
                                <!-- <a href="javascript:void()" title="Update Status" onclick="showOrderStatusUpdateModal('{{ route('admin.contact.query.response',['query_id'=>encrypt($query->id)]) }}')">
                                    <i class="fa fa-plus-square"></i>
                                </a> -->
                            </td>
                        </tr>
                    @endforeach
                </tbody>
                <tfoot>
                <tr>
                    <th>Sr. No.</th>
                    <th>Name </th>
                    <th>Email</th>
                    <th>Query</th>
                    <th>Query Date/Time</th>
                    <th>Responded</th>
                    <th>Action</th>
                </tr>
                </tfoot>
                </table>
                    </div>

                </div>
            </div>
        </div>
        </div>
    </div>

    <div class="modal inmodal fade" id="reply-contact-query-form-modal" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Reply Contact Query </h4>
                    <!-- <small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small> -->
                </div>
                <div class="modal-body">
                    <form id="contact-query-response-form">
                        @csrf
                        <input type="hidden" name="query_id" id="query_id" value="">
                        <div class="form-group  row">
                            <label class="col-sm-3 col-form-label">Reply Message :</label>
                            <div class="col-sm-9">
                                <textarea type="text" name="reply_contact_query" id="reply_contact_query" rows="8" class="form-control" placeholder="Response message goes here ..."></textarea>
                            </div>
                        </div>
                    </form>
                </div>
                        
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="validateAndSubmitContactQueryReplyForm()">Submit</button>
                </div>
            </div>
        </div>
    </div>
    
    <!-- Order Status update Modal -->
    <div class="modal inmodal fade" id="contact-query-data-modal" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title">Contact Query</h4>
                    <!-- <small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small> -->
                </div>
                <div class="modal-body">
                    <input type="hidden" id="contact_query_id" value="">
                    <div class="form-group  row">
                        <label class="col-sm-2 col-form-label">Query :</label>
                        <div class="col-sm-10">
                            <textarea type="text" id="contact_query" rows="6" readonly class="form-control" placeholder="Response message goes here ..."></textarea>
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group row" id="contact_query_response" style="display: none;">
                        <label class="col-sm-2 col-form-label">Response :</label>
                        <div class="col-sm-10">
                            <textarea type="text" id="admin_response" rows="6" readonly class="form-control" placeholder="Response message goes here ..."></textarea>
                        </div>
                    </div>
                </div>
                    
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" onclick="showContactQueryReplyFormModal()">Reply</button>
                </div>
            </div>
        </div>
    </div>

<script src="{{ asset('admin_assets/js/plugins/dataTables/datatables.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>

<!-- Page-Level Scripts -->
<script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                    { extend: 'copy'},
                    {extend: 'csv'},
                    {extend: 'excel', title: 'ExampleFile'},
                    {extend: 'pdf', title: 'ExampleFile'},

                    {extend: 'print',
                     customize: function (win){
                            $(win.document.body).addClass('white-bg');
                            $(win.document.body).css('font-size', '10px');

                            $(win.document.body).find('table')
                                    .addClass('compact')
                                    .css('font-size', 'inherit');
                    }
                    }
                ]

            });

        });

        function showQueryDataModal(query_message, query_id, admin_response) {
            $("textarea#contact_query").val('');
            $("textarea#admin_response").val('');
            $("#contact_query_response").hide();
            $("textarea#contact_query").val(query_message);
            if (admin_response != '') {
                
                $("textarea#admin_response").val(admin_response);
                $("#contact_query_response").show();
            }
            $("#contact_query_id").val(query_id);
            $("#contact-query-data-modal").modal('toggle');
        }

        function showContactQueryReplyFormModal(query_id=null) {
            $("textarea#reply_contact_query").val();
            $("#contact-query-data-modal").modal('hide');
            if (query_id == null) {
                $("#query_id").val($("#contact_query_id").val());
            } else {
                $("#query_id").val(query_id);
            }
            $("#reply-contact-query-form-modal").modal('toggle');
        }

        function validateAndSubmitContactQueryReplyForm() {
            $.ajax({
                url  : "{{ route('admin.contact.query.response') }}",
                type : "POST",
                data : $("#contact-query-response-form").serialize()
            })
            .done(function(response){
                console.log(response);
                window.location.reload();
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }
        
        function validateAndSubmitOrderStatusUpdateForm() {
            $.ajax({
                url  : $("#contact-query-response-form").attr('action'),
                type : "PUT",
                data : $("#contact-query-response-form").serialize()
            })
            .done(function(response){
                console.log(response);
                window.location.reload();
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }
    </script>
@endsection

resources/views/admin/custom-email-notification.blade.php
@extends('layouts.admin.main')
@section('title','Order List')
@section('content')
<link href="{{ asset('admin_assets/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Custom Email</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard') }}">Dashboard</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Custom Email Form</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
                @if(session()->has('success'))
                    <div class="col-sm-12">
                        <div class="alert alert-success">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                &times;
                            </button>
                            <strong>
                                Success
                            </strong>
                            {{ session('success') }}
                        </div>
                    </div>
                @endif
                @if(session()->has('error'))
                    <div class="col-sm-12">
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                &times;
                            </button>
                            <strong>
                                Error !
                            </strong>
                            {{ session('error') }}
                        </div>
                    </div>
                @endif
                @if (count($errors) > 0)
                    <div class="col-sm-12">
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                &times;
                            </button>
                            <h4><i class="icon fa fa-ban"></i> Error!</h4>
                            @foreach($errors->all() as $error)
                            {{ $error }} <br>
                            @endforeach  
                        </div>
                    </div>
                    
                @endif
                <div class="col-lg-12">
                <div class="ibox ">
                    <div class="ibox-title">
                        <h5>Order list with data</h5>
                        <div class="ibox-tools">
                        
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12">
                                    <form id="add-order-data-form" action="{{ route('admin.send.custom.email.notification') }}" method="POST">
                                        @csrf
                                        <div class="form-group  row">
                                            <label class="col-sm-4 col-form-label">Name :</label>
                                            <div class="col-sm-8">
                                                <input type="text" name="name" id="name" class="form-control" placeholder="Name">
                                                @if ($errors->has('name'))
                                                    <span style="color: red;">{{ $errors->first('name') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="hr-line-dashed"></div>
                                        <div class="form-group  row">
                                            <label class="col-sm-4 col-form-label">Email :</label>
                                            <div class="col-sm-8">
                                                <input type="email" name="email" id="email" class="form-control" placeholder="Email">
                                                @if ($errors->has('email'))
                                                    <span style="color: red;">{{ $errors->first('email') }}</span>
                                                @endif
                                            </div>

                                        </div>
                                        <div class="hr-line-dashed"></div>
                                        <div class="form-group  row">
                                            <label class="col-sm-4 col-form-label">Email :</label>
                                            <div class="col-sm-8">
                                                <textarea class="form-control" name="message" id="message" cols="30" rows="10">{{ old('message') }}</textarea>
                                                @if ($errors->has('message'))
                                                    <span style="color: red;">{{ $errors->first('message') }}</span>
                                                @endif
                                            </div>
                                        </div>
                                        <div class="hr-line-dashed"></div>
                                        <div class="form-group row pull-right">
                                            <div class="col-12">
                                                <input class="btn btn-success pull-right" type="submit" value="Send">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/dashboard.blade.php
@extends('layouts.admin.main')
@section('title','Dashboard')
@section('content')

    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-title">
                        <!-- <span class="label label-success float-right">Monthly</span> -->
                        <h5>Orders</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins">{{ \App\Models\Order::all()->count() }}</h1>
                        <!-- <div class="stat-percent font-bold text-success">98% <i class="fa fa-bolt"></i></div> -->
                        <small>Total orders</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-title">
                        <!-- <span class="label label-info float-right">Annual</span> -->
                        <h5>Orders Delivered</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins">{{ \App\Models\Order::whereHas('order_status',function($query){
                            $query->where('order_status','delivered'); })->get()->count() }}</h1>
                        <!-- <div class="stat-percent font-bold text-info">20% <i class="fa fa-level-up"></i></div> -->
                        <small>Orders delivered</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-title">
                        <!-- <span class="label label-primary float-right">Today</span> -->
                        <h5>Contact Queries</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins">{{ \App\Models\ContactQuery::all()->count() }}</h1>
                        <!-- <div class="stat-percent font-bold text-navy">44% <i class="fa fa-level-up"></i></div> -->
                        <small>Total contact queries</small>
                    </div>
                </div>
            </div>
            <div class="col-lg-3">
                <div class="ibox ">
                    <div class="ibox-title">
                        <!-- <span class="label label-danger float-right">Low value</span> -->
                        <h5>Responded To Queries</h5>
                    </div>
                    <div class="ibox-content">
                        <h1 class="no-margins">{{ \App\Models\ContactQuery::where('admin_responded',1)->get()->count() }}</h1>
                        <!-- <div class="stat-percent font-bold text-danger">38% <i class="fa fa-level-down"></i></div> -->
                        <small>Total query response</small>
                    </div>
                </div>
    		</div>
        </div>
    </div>
    <!-- <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-sm-4">
            <h2>This is main title</h2>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="index.html">This is</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>Breadcrumb</strong>
                </li>
            </ol>
        </div>
        <div class="col-sm-8">
            <div class="title-action">
                <a href="" class="btn btn-primary">This is action area</a>
            </div>
        </div>
    </div>

    <div class="wrapper wrapper-content">
        <div class="middle-box text-center animated fadeInRightBig">
            <h3 class="font-bold">This is page content</h3>
            <div class="error-desc">
                You can create here any grid layout you want. And any variation layout you imagine:) Check out
                main dashboard and other site. It use many different layout.
                <br/><a href="{{ route('admin.dashboard') }}" class="btn btn-primary m-t">Dashboard</a>
            </div>
        </div>
    </div> -->
@endsection()