routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use \App\Http\Controllers\Admin\Auth\LoginController as AdminLoginController;
use \App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //  Getting banner list
    $banners    =   \App\Models\Banner::where('is_active',1)->get();

    return view('welcome',compact(['banners']));
})->name('homepage');

Route::get('/about-us', function () {
    return view('about-us');
})->name('about-us');

Route::prefix('services/')->as('services.')->group(function () {
   
    Route::get('freight-forwarding', function () {
        return view('services.freight-forwarding');
    })->name('freight.forwarding');
    
    Route::get('ocean-freight', function () {
        return view('services.ocean-freight');
    })->name('freight.ocean');
    
    Route::get('air-freight', function () {
        return view('services.air-freight');
    })->name('freight.air');
    
    Route::get('trucking-freight', function () {
        return view('services.trucking-freight');
    })->name('freight.trucking');
    
    Route::get('warehouse-and-distribution', function () {
        return view('services.warehouse-distribution');
    })->name('warehouse.distribution');

});

// Route::get('/blogs', function () {
//     return view('blogs');
// })->name('blogs');

Route::get('/blogs/{slug?}',[HomeController::class,'blogDetails'])->name('blogs.details');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//  Route to track order details
Route::get('order/tracking/details',[HomeController::class,'index'])->name('order.tracking.details');

//  Route to save contact query by user
Route::post('contact/query',[HomeController::class,'saveContactQuery'])->name('contact.query.save');

/*----------------------------------------------
 *  ADMIN Routes
 * ---------------------------------------------
 * */

Route::prefix('admin/')->as('admin.')->group(function(){

    Route::get('/',function(){
        return redirect()->route('admin.login.show');
    });

    //  Login Route
    Route::get('login',[AdminLoginController::class,'create'])->name('login.show');
    
    //  Login Post Route
    Route::post('login',[AdminLoginController::class,'store'])->name('login');
    
    //  Forgot Password Form Route
    Route::get('forgot/password',[ForgotPasswordController::class,'forgotPasswordForm'])->name('forgot.password');
    
    //  Forgot Password Form Submit and reset password link Route
    Route::post('forgot/password',[ForgotPasswordController::class,'sendResetPasswordLink'])->name('forgot.password.submit');
    
    //  Reset Password form Route
    Route::get('reset/password/{token}',[ResetPasswordController::class,'resetPasswordForm'])->name('reset.password.form');
    
    //  Reset Password form submit Route
    Route::post('reset/password',[ResetPasswordController::class,'resetPassword'])->name('reset.password.form.submit');

    /*--------------------------------------------------
     *  ADMIN Auth Routes
     *--------------------------------------------------
     */
    Route::middleware('auth')->group(function(){

        //  Logout Route
        Route::post('logout',[AdminLoginController::class,'destroy'])->name('logout');

        //  Dashboard Route
        Route::get('dashboard',[AdminController::class,'dashboard'])->name('dashboard');
        
        //  Update Password Form Route
        Route::get('update/password',[AdminController::class,'changePasswordForm'])->name('update.password.form');
        
        //  Update Password Form Submit Route
        Route::post('update/password',[AdminController::class,'submitChangePasswordForm'])->name('update.password.form.submit');

        //  Order Routes Group
        Route::prefix('order/')->as('order.')->group(function(){

            //  Order List
            Route::get('list/{type}',[AdminController::class,'orderList'])->name('list');
            
            //  Create Order
            Route::post('data',[AdminController::class,'createOrder'])->name('create');
            
            //  Import Order Data
            Route::post('data/import',[AdminController::class,'importOrderData'])->name('import.data');

            //  Order Status Data
            Route::get('status/data/{order_id}',[AdminController::class,'orderStatusData'])->name('status.data');

            //  Order Data to Edit
            Route::get('edit/{order_id}',[AdminController::class,'editOrderData'])->name('edit');
            
            //  Update Order Data
            Route::put('update/{order_id}',[AdminController::class,'updateOrderData'])->name('update');

            //  Update Order Status
            Route::put('status/update/{order_id}',[AdminController::class,'updateOrderStatus'])->name('update.status');

        });

        //  Banner List route
       //  Route::get('banners/list',[AdminController::class,'bannerList'])->name('banners.list');
        
        //  Add Banner route
        // Route::post('banners/add',[AdminController::class,'addBanner'])->name('banners.add');
        
        //  Delete Banner route
        // Route::delete('banners/delete/{banner_id}',[AdminController::class,'destroyBanner'])->name('banners.destroy');
        
        //  Contact Queries route
        Route::get('contact/queries',[AdminController::class,'contactQueries'])->name('contact.queries');
        
        //  Contact Query Admin Response route
        Route::post('contact/queries/response',[AdminController::class,'contactQueryResponse'])->name('contact.query.response');
        
        //  Resource route of Sub Admin
        Route::resource('sub/admin', SubAdminController::class)->names('sub.admin')->parameters([
            'admin' =>  'id'
        ]);
        
        //  Resource route of Sub Admin
        Route::resource('blogs', BlogController::class)->names('blogs')->parameters([
             'blog' =>  'id'
        ]);
        
        //  Activate, Deactivate, Delete Sub Admin route
        Route::get('sub/admin/activate/deactivate/delete/{action}/{data_id}',[AdminController::class,'activateDeactivateDeleteSubAdmin'])->name('sub.admin.activate.deactivate.delete');

        //  Custom Email Notification Form
        // Route::get('custom/email/notification',[AdminController::class,'customEmailNotificationForm'])->name('custom.email.notification');
        Route::get('custom/email/notification',function(){
            return view('admin.custom-email-notification');
        })->name('custom.email.notification');
        
        //  Custom Email Notification Form Submit
        Route::post('custom/email/notification',[AdminController::class,'sendCustomEmailNotification'])->name('send.custom.email.notification');
    });
});

app/Http/Controllers/Admin/SubAdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Notifications\Admin\SubAdminCreated;
use App\Http\Requests\SubAdminFormRequest;

class SubAdminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //  Getting all sub admins list
        $subAdmins  =   Admin::where('role','!=',1)->get();

        //  Returning view with sub admin list
        return view('admin.sub-admin.list',compact(['subAdmins']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SubAdminFormRequest $request)
    {
        try {

            //  Beginning DB transaction
            \DB::beginTransaction();

            //  Inserting sub admin data into admins table
            $subAdmin   =   Admin::create([
                                    'name'      =>  trim($request->name),
                                    'email'     =>  trim($request->email),
                                    'password'  =>  bcrypt($request->password),
                                    'role'      =>  2,
                                    'created_at'=>  date('Y-m-d H:i:s'),
                                    'updated_at'=>  date('Y-m-d H:i:s')
                                ]);

            //  Mail to be send on the created sub admin's email id
            $subAdmin->notify(new SubAdminCreated('add', $request->name, $request->email, $request->password));

            //  Committing DB transaction 
            \DB::commit();

            //  Returning success response
            return response()->json(['status'=>true,'message'=>'Sub Admin has been created successfully.']);

        } catch (\Exception $e) {

            //  Rolling back DB transaction
            \DB::rollback();

            //  Returning server error response
            return response()->json(['status'=>false,'message'=>$e->getMessage()]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {

            //  Getting sub admin's data to edit
            $subAdminData   =   Admin::find(decrypt($id));
            
            //  Returning view with data
            return view('admin.sub-admin.edit-sub-admin-data',compact(['subAdminData']));

        } catch (\Exception $e) {
            
            //  Returning server error response
            return response()->json(['status'=>false,'message'=>$e->getMessage()]);
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SubAdminFormRequest $request, $id)
    {
        try {

            //  Beginning DB transaction
            \DB::beginTransaction();

            //  Creating sub admin object by getting data of sub admin using Admin model
            $subAdmin   =   Admin::find(decrypt($id));

            //  Assigning updated values of sub admin to object
            $subAdmin->name     =   trim($request->name);
            $subAdmin->email    =   trim($request->email);

            //  If request has password then
            if ($request->has('password') && $request->password != null) {
                
                $subAdmin->password     =   bcrypt($request->password);
            }

            //  Saving updated data of sub admin
            $subAdmin->save();

            //  Mail to be send on the created sub admin's email id
            $subAdmin->notify(new SubAdminCreated('update', $request->name, $request->email, $request->password));

            //  Committing DB transaction 
            \DB::commit();

            //  Returning success response
            return response()->json(['status'=>true,'message'=>'Sub Admin data has been updated successfully.']);

        } catch (\Exception $e) {

            //  Rolling back DB transaction
            \DB::rollback();

            //  Returning server error response
            return response()->json(['status'=>false,'message'=>$e->getMessage()]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/sub-admin/edit-sub-admin-data.blade.php
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title">Edit Sub Admin</h4>
            <!-- <small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small> -->
        </div>
        <div class="modal-body">
            <form id="edit-sub-admin-form" action="{{ route('admin.sub.admin.update',['id'=>encrypt($subAdminData->id)]) }}">
                @method('PUT')
                @csrf
                <input type="hidden" name="action" value="edit">
                <input type="hidden" name="admin_id" value="{{ encrypt($subAdminData->id) }}">
                <div class="form-group  row">
                    <label class="col-sm-4 col-form-label">Name :</label>
                    <div class="col-sm-8">
                        <input type="text" name="name" id="name" class="form-control" value="{{ $subAdminData->name }}" placeholder="Enter Name">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group  row">
                    <label class="col-sm-4 col-form-label">Email :</label>
                    <div class="col-sm-8">
                        <input type="email" name="email" id="email" class="form-control" value="{{ $subAdminData->email }}" placeholder="Enter Email">
                    </div>
                </div>
                <div class="hr-line-dashed"></div>
                <div class="form-group  row">
                    <label class="col-sm-4 col-form-label">Password :</label>
                    <div class="col-sm-8">
                        <input type="text" name="password" id="password" class="form-control" placeholder="Enter Password">
                    </div>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                <button type="button" onclick="validateAndSubmitUpdateForm()" class="btn btn-primary">Update</button>
            </div>
        </form>
    </div>
</div>

resources/views/admin/sub-admin/list.blade.php
@extends('layouts.admin.main')
@section('title','Sub Admin List')
@section('content')
<link href="{{ asset('admin_assets/css/plugins/dataTables/datatables.min.css') }}" rel="stylesheet">
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Sub Admin List</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Sub Admins</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>Sub Admin list with data</h5>
                <div class="ibox-tools">
                    <!-- <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#" class="dropdown-item">Config option 1</a>
                        </li>
                        <li><a href="#" class="dropdown-item">Config option 2</a>
                        </li>
                    </ul> -->
                    <button type="button" href="javascript:void()" data-target="#add-sub-admin-data-modal" data-toggle="modal" class="btn btn-w-m btn-primary" style="margin-top: -7px;">
                        Add Sub Admin
                    </button>
                </div>
            </div>
            <div class="ibox-content">

                <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover dataTables-example" >
            <thead>
            <tr>
                <th>Sr. No.</th>
                <th>Name </th>
                <th>Email</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($subAdmins as $key => $sub_admin)
                    <tr class="gradeX">
                        <td>
                            {{ $key+1 }}
                        </td>
                        <td>
                            {{ $sub_admin->name }}
                        </td>
                        <td>
                            {{ $sub_admin->email }}
                        </td>
                        <td>
                            @if ($sub_admin->is_active)
                                <span class="badge badge-success">Active</span>
                            @else
                                <span class="badge badge-warning">Inactive</span>
                            @endif
                        </td>
                        <td>
                            <!-- <a href="javascript:void(0)" title="View Order Status" onclick="showOrderStatusData('{{ route('admin.order.status.data',['order_id'=>encrypt($sub_admin->id)]) }}')">
                                <i class="fa fa-eye"></i>
                            </a>
                            &nbsp;|&nbsp; -->
                            <a href="javascript:void(0)" title="Edit Data" onclick="getSubAdminDataToEdit('{{ route('admin.sub.admin.edit',['id'=>encrypt($sub_admin->id)]) }}')">
                                <i class="fa fa-pencil"></i>
                            </a>
                            &nbsp;|&nbsp;
                            <a href="javascript:void(0)" title="Update Status" onclick="activateDeactivateDeleteSubAdminData('{{ route('admin.sub.admin.activate.deactivate.delete',['action'=>encrypt('delete'),'data_id'=>encrypt($sub_admin->id)]) }}')">
                                <i class="fa fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
            <tfoot>
            <tr>
            <th>Sr. No.</th>
                <th>Name </th>
                <th>Email</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
            </tfoot>
            </table>
                </div>

            </div>
        </div>
    </div>
    </div>
</div>

<div class="modal inmodal fade" id="add-sub-admin-data-modal" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Add Sub Admin</h4>
                <!-- <small class="font-bold">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</small> -->
            </div>
            <div class="modal-body">
                <form id="add-sub-admin-form">
                    @csrf
                    <input type="hidden" name="action" value="add">
                    <div class="form-group  row">
                        <label class="col-sm-4 col-form-label">Name :</label>
                        <div class="col-sm-8">
                            <input type="text" name="name" id="name" class="form-control" placeholder="Enter Name">
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group  row">
                        <label class="col-sm-4 col-form-label">Email :</label>
                        <div class="col-sm-8">
                            <input type="email" name="email" id="email" class="form-control" placeholder="Enter Email">
                        </div>
                    </div>
                    <div class="hr-line-dashed"></div>
                    <div class="form-group  row">
                        <label class="col-sm-4 col-form-label">Password :</label>
                        <div class="col-sm-8">
                            <input type="text" name="password" id="password" class="form-control" placeholder="Enter Password">
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-white" data-dismiss="modal">Close</button>
                    <button type="button" onclick="validateAndSubmitForm()" class="btn btn-primary">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal to Edit Sub Admin Data -->
<div class="modal inmodal fade" id="edit-sub-admin-data-modal" tabindex="-1" role="dialog"  aria-hidden="true"></div>

<script src="{{ asset('admin_assets/js/plugins/dataTables/datatables.min.js') }}"></script>
<script src="{{ asset('admin_assets/js/plugins/dataTables/dataTables.bootstrap4.min.js') }}"></script>

<!-- Page-Level Scripts -->
<script>
        $(document).ready(function(){
            $('.dataTables-example').DataTable({
                pageLength: 25,
                responsive: true,
                dom: '<"html5buttons"B>lTfgitp',
                buttons: [
                ]

            });

        });

        function validateAndSubmitForm() {
            $("#add-sub-admin-data-modal").modal('toggle');
            $.ajax({
                url  : "{{ route('admin.sub.admin.store') }}",
                type : "POST",
                data : $("#add-sub-admin-form").serialize()
            })
            .done(function(response){
                if (response.status) {
                    swal({
                        title : "Added",
                        text : response.message,
                        type : "success"
                    }, function(){
                        window.location.reload();
                    });
                } else {
                    swal({
                        title : "Error!",
                        text : response.message,
                        type : "error"
                    });
                }
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }

        function getSubAdminDataToEdit(url) {
            $.ajax({
                url  : url,
                type : "GET"
            })
            .done(function(response){
                $("#edit-sub-admin-data-modal").html(response);
                $("#edit-sub-admin-data-modal").modal('toggle');
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }
       
        function validateAndSubmitUpdateForm() {
            $("#edit-sub-admin-data-modal").modal('toggle');
            $.ajax({
                url  : $("#edit-sub-admin-form").attr('action'),
                type : "PUT",
                data : $("#edit-sub-admin-form").serialize()
            })
            .done(function(response){
                console.log(response);
                alert(response.message);
                window.location.reload();
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }
        
        function activateDeactivateDeleteSubAdminData(url) {
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover deleted sub admin data!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function () {
                $.ajax({
                    url  : url,
                    type : "GET"
                })
                .done(function(response){
                    console.log(response);
                    if (response.status) {
                        swal({
                            title : "Deleted",
                            text : response.message,
                            type : "success"
                        }, function(){
                            window.location.reload();
                        });
                    } else {
                        swal({
                            title : "Error!",
                            text : response.message,
                            type : "error"
                        });
                    }
                })
                .fail(function(response){
                    $.each(response.responseJSON.errors,function(index,value){
                        alert(value);
                    });
                })
                .always(function(){

                });
            });
        }


        function showOrderStatusUpdateModal(action_url) {
            $("#update-order-status-form").attr('action','');
            $("#update-order-status-form").attr('action',action_url);
            $("#order-status-update-modal").modal('toggle');
        }
        
        
        function validateAndSubmitOrderStatusUpdateForm() {
            $.ajax({
                url  : $("#update-order-status-form").attr('action'),
                type : "PUT",
                data : $("#update-order-status-form").serialize()
            })
            .done(function(response){
                console.log(response);
                alert(response.message);
                window.location.reload();
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }


        function showOrderStatusData(url) {
            $.ajax({
                url  : url,
                type : "GET"
            })
            .done(function(response){
                $("#order-status-data-modal").html(response);
                $("#order-status-data-modal").modal('toggle');
            })
            .fail(function(response){
                $.each(response.responseJSON.errors,function(index,value){
                    alert(value);
                });
            })
            .always(function(){

            });
        }
    </script>
@endsection