routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use \App\Http\Controllers\Admin\Auth\LoginController as AdminLoginController;
use \App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\Auth\ForgotPasswordController;
use App\Http\Controllers\Admin\Auth\ResetPasswordController;
use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\HomeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //  Getting banner list
    $banners    =   \App\Models\Banner::where('is_active',1)->get();

    return view('welcome',compact(['banners']));
})->name('homepage');

Route::get('/about-us', function () {
    return view('about-us');
})->name('about-us');

Route::prefix('services/')->as('services.')->group(function () {
   
    Route::get('freight-forwarding', function () {
        return view('services.freight-forwarding');
    })->name('freight.forwarding');
    
    Route::get('ocean-freight', function () {
        return view('services.ocean-freight');
    })->name('freight.ocean');
    
    Route::get('air-freight', function () {
        return view('services.air-freight');
    })->name('freight.air');
    
    Route::get('trucking-freight', function () {
        return view('services.trucking-freight');
    })->name('freight.trucking');
    
    Route::get('warehouse-and-distribution', function () {
        return view('services.warehouse-distribution');
    })->name('warehouse.distribution');

});

// Route::get('/blogs', function () {
//     return view('blogs');
// })->name('blogs');

Route::get('/blogs/{slug?}',[HomeController::class,'blogDetails'])->name('blogs.details');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';


//  Route to track order details
Route::get('order/tracking/details',[HomeController::class,'index'])->name('order.tracking.details');

//  Route to save contact query by user
Route::post('contact/query',[HomeController::class,'saveContactQuery'])->name('contact.query.save');

/*----------------------------------------------
 *  ADMIN Routes
 * ---------------------------------------------
 * */

Route::prefix('admin/')->as('admin.')->group(function(){

    Route::get('/',function(){
        return redirect()->route('admin.login.show');
    });

    //  Login Route
    Route::get('login',[AdminLoginController::class,'create'])->name('login.show');
    
    //  Login Post Route
    Route::post('login',[AdminLoginController::class,'store'])->name('login');
    
    //  Forgot Password Form Route
    Route::get('forgot/password',[ForgotPasswordController::class,'forgotPasswordForm'])->name('forgot.password');
    
    //  Forgot Password Form Submit and reset password link Route
    Route::post('forgot/password',[ForgotPasswordController::class,'sendResetPasswordLink'])->name('forgot.password.submit');
    
    //  Reset Password form Route
    Route::get('reset/password/{token}',[ResetPasswordController::class,'resetPasswordForm'])->name('reset.password.form');
    
    //  Reset Password form submit Route
    Route::post('reset/password',[ResetPasswordController::class,'resetPassword'])->name('reset.password.form.submit');

    /*--------------------------------------------------
     *  ADMIN Auth Routes
     *--------------------------------------------------
     */
    Route::middleware('auth')->group(function(){

        //  Logout Route
        Route::post('logout',[AdminLoginController::class,'destroy'])->name('logout');

        //  Dashboard Route
        Route::get('dashboard',[AdminController::class,'dashboard'])->name('dashboard');
        
        //  Update Password Form Route
        Route::get('update/password',[AdminController::class,'changePasswordForm'])->name('update.password.form');
        
        //  Update Password Form Submit Route
        Route::post('update/password',[AdminController::class,'submitChangePasswordForm'])->name('update.password.form.submit');

        //  Order Routes Group
        Route::prefix('order/')->as('order.')->group(function(){

            //  Order List
            Route::get('list/{type}',[AdminController::class,'orderList'])->name('list');
            
            //  Create Order
            Route::post('data',[AdminController::class,'createOrder'])->name('create');
            
            //  Import Order Data
            Route::post('data/import',[AdminController::class,'importOrderData'])->name('import.data');

            //  Order Status Data
            Route::get('status/data/{order_id}',[AdminController::class,'orderStatusData'])->name('status.data');

            //  Order Data to Edit
            Route::get('edit/{order_id}',[AdminController::class,'editOrderData'])->name('edit');
            
            //  Update Order Data
            Route::put('update/{order_id}',[AdminController::class,'updateOrderData'])->name('update');

            //  Update Order Status
            Route::put('status/update/{order_id}',[AdminController::class,'updateOrderStatus'])->name('update.status');

        });

        //  Banner List route
       //  Route::get('banners/list',[AdminController::class,'bannerList'])->name('banners.list');
        
        //  Add Banner route
        // Route::post('banners/add',[AdminController::class,'addBanner'])->name('banners.add');
        
        //  Delete Banner route
        // Route::delete('banners/delete/{banner_id}',[AdminController::class,'destroyBanner'])->name('banners.destroy');
        
        //  Contact Queries route
        Route::get('contact/queries',[AdminController::class,'contactQueries'])->name('contact.queries');
        
        //  Contact Query Admin Response route
        Route::post('contact/queries/response',[AdminController::class,'contactQueryResponse'])->name('contact.query.response');
        
        //  Resource route of Sub Admin
        Route::resource('sub/admin', SubAdminController::class)->names('sub.admin')->parameters([
            'admin' =>  'id'
        ]);
        
        //  Resource route of Sub Admin
        Route::resource('blogs', BlogController::class)->names('blogs')->parameters([
             'blog' =>  'id'
        ]);
        
        //  Activate, Deactivate, Delete Sub Admin route
        Route::get('sub/admin/activate/deactivate/delete/{action}/{data_id}',[AdminController::class,'activateDeactivateDeleteSubAdmin'])->name('sub.admin.activate.deactivate.delete');

        //  Custom Email Notification Form
        // Route::get('custom/email/notification',[AdminController::class,'customEmailNotificationForm'])->name('custom.email.notification');
        Route::get('custom/email/notification',function(){
            return view('admin.custom-email-notification');
        })->name('custom.email.notification');
        
        //  Custom Email Notification Form Submit
        Route::post('custom/email/notification',[AdminController::class,'sendCustomEmailNotification'])->name('send.custom.email.notification');
    });
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;

    //  Creating blog image accessor 
    public function getImageAttribute($image)
    {
        //  Returning image after appending storage path to blog image
        return \Storage::url($image);
    }
}

app/Http/Controllers/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AddBlogRequest;
use Illuminate\Http\Request;
use App\Models\Blog;
use Storage;
use Str;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //  Getting all blog list
        $blogs  =   Blog::all();

        //  Returning view of blog list
        return view('admin.blogs.blog_list',compact(['blogs']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //  Returning blog form
        return view('admin.blogs.add-new-blog-form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddBlogRequest $request)
    {
        try {
            //  Creating blog model object
            $blog   =   new Blog;

            //  Updating data to related key
            $blog->title    =   trim($request->blog_title);
            $blog->content  =   trim($request->blog_content);
            $blog->slug     =   Str::of($request->blog_title)->slug('-');

            //  Saving blog image to storage folder
            $blog->image    =   Storage::put('images/blogs/',$request->file('blog_image'));

            //  Saving blog data
            $blog->save();

            //  Returning back with success message
            return back()->with('success','Blog has been added successfully.');

        } catch (\Exception $e) {
            
            //  Returning back with error message
            return back()->with('error',$e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //  Getting blog data
        $blogData   =   Blog::find(decrypt($id));

        //  Returning view with blog data
        return view('admin.blogs.edit-blog',compact(['blogData']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            //  Getting blog data object using blog model
            $blog   =   Blog::find(decrypt($id));

            //  Updating data of blog
            $blog->title    =   trim($request->blog_title);
            $blog->content  =   trim($request->blog_content);
            $blog->slug     =   Str::of($request->blog_title)->slug('-');

            //  If request has file then
            if ($request->hasFile('blog_image') && !empty($request->blog_image)) {
                
                //  Deleting previously saved image in storage folder
                Storage::delete($blog->image);

                //  Putting new image to storage folder
                $blog->image    =   Storage::put('images/blogs/',$request->file('blog_image'));
            }

            //  Saving updated data
            $blog->save();

            //  Returning back with success message
            return back()->with('success','Blog data has been updated successfully.');

        } catch (\Exception $e) {
            
            //  Returning back with server error exception message
            return back()->with('error',$e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            //  Getting blog data
            $blog   =   Blog::find(decrypt($id));

            //  Deleting blog image from storage folder
            Storage::delete($blog->image);

            //  Deleting blog data
            $blog->delete();

            //  Returning success response
            return response()->json([
                'status'    =>  true,
                'title'     =>  'Deleted',
                'message'   =>  'Blog deleted successfully.'
            ]);

        } catch (\Exception $e) {
            //  Returning server error response
            return response()->json([
                'status'    =>  false,
                'title'     =>  "Internal Server Error!",
                'message'   =>  $e->getMessage()
            ]);
        }
    }
}

resources/views/admin/blogs/add-new-blog-form.blade.php
@extends('layouts.admin.main')
@section('title','Add Blog')
@section('content')

<link href="{{ asset('admin_assets/css/plugins/summernote/summernote-bs4.css') }}" rel="stylesheet">
<!-- SUMMERNOTE -->
<script src="{{ asset('admin_assets/js/plugins/summernote/summernote-bs4.js') }}"></script>

<style>
    .validation_error_message{
        color: red;
    }
</style>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Add New Blog</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ route('admin.blogs.index') }}">Blogs</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Add Blog</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            @if (session()->has('success'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <strong>
                        Success!
                    </strong>
                    {{ session('success') }}
                </div>
            @elseif (session()->has('error'))
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <strong>
                        Error!
                    </strong>
                    {{ session('error') }}
                </div>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Add Blog Form</h5>
                    <div class="ibox-tools">
                        <a type="button" href="{{ route('admin.blogs.index') }}" class="btn btn-w-m btn-primary" style="margin-top: -7px;">
                            Blog List
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="add-blog-form" action="{{ route('admin.blogs.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group  row">
                                    <label class="col-sm-4 col-form-label">Blog Title :</label>
                                    <div class="col-sm-8">
                                        <input type="text" name="blog_title" id="blog_title" class="form-control" placeholder="Blog Title" value="{{ old('blog_title') }}">
                                        @if ($errors->has('blog_title'))
                                            <span class="validation_error_message">{{ $errors->first('blog_title') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                                <div class="form-group  row">
                                    <label class="col-sm-4 col-form-label">Blog Image :</label>
                                    <div class="col-sm-8">
                                        <input type="file" name="blog_image" id="blog_image" class="form-control">
                                        @if ($errors->has('blog_image'))
                                            <span class="validation_error_message">{{ $errors->first('blog_image') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                                <div class="form-group  row">
                                    <label class="col-sm-4 col-form-label">Blog Content :</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control summernote-editor" rows="8" name="blog_content" id="blog_content" class="form-control" placeholder="Blog content goes here ...">{{ old('blog_content') }}</textarea>
                                        @if ($errors->has('blog_content'))
                                            <span class="validation_error_message">{{ $errors->first('blog_content') }}</span>
                                        @endif
                                    </div>
                                </div>
                                
                                <div class="hr-line-dashed"></div>
                                <div class="form-group  row">
                                    <div class="col-sm-12">
                                        <input type="submit" class="btn btn-primary">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){

        $('.summernote-editor').summernote({
                                    height: 250,
                                    focus: true
                                });

    });
</script>

@endsection

resources/views/admin/blogs/edit-blog.blade.php
@extends('layouts.admin.main')
@section('title','Add Blog')
@section('content')

<style>
    .validation_error_message{
        color: red;
    }
</style>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edit Blog</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('admin.dashboard') }}">Dashboard</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ route('admin.blogs.index') }}">Blogs</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Edit Blog</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            @if (session()->has('success'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <strong>
                        Success!
                    </strong>
                    {{ session('success') }}
                </div>
            @elseif (session()->has('error'))
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                        &times;
                    </button>
                    <strong>
                        Error!
                    </strong>
                    {{ session('error') }}
                </div>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox ">
                <div class="ibox-title">
                    <h5>Edit Blog Form</h5>
                    <div class="ibox-tools">
                        <a type="button" href="{{ route('admin.blogs.create') }}" class="btn btn-w-m btn-primary" style="margin-top: -7px;">
                            Add New Blog
                        </a>
                        <a type="button" href="{{ route('admin.blogs.index') }}" class="btn btn-w-m btn-primary" style="margin-top: -7px;">
                            Blog List
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="add-blog-form" action="{{ route('admin.blogs.update',['blog'=>encrypt($blogData->id)]) }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group  row">
                                    <label class="col-sm-4 col-form-label">Blog Title :</label>
                                    <div class="col-sm-8">
                                        <input type="text" name="blog_title" id="blog_title" class="form-control" placeholder="Blog Title" value="{{ $blogData->title }}">
                                        @if ($errors->has('blog_title'))
                                            <span class="validation_error_message">{{ $errors->first('blog_title') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                                <div class="form-group  row">
                                    <label class="col-sm-4 col-form-label">Blog Image :</label>
                                    <div class="col-sm-8">
                                        <input type="file" name="blog_image" id="blog_image" class="form-control">
                                        @if ($errors->has('blog_image'))
                                            <span class="validation_error_message">{{ $errors->first('blog_image') }}</span>
                                        @endif
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                                <div class="form-group  row">
                                    <label class="col-sm-4 col-form-label">Blog Content :</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control ck_editor" rows="8" name="blog_content" id="blog_content" class="form-control" placeholder="Blog content goes here ...">{{ $blogData->content }}</textarea>
                                        @if ($errors->has('blog_content'))
                                            <span class="validation_error_message">{{ $errors->first('blog_content') }}</span>
                                        @endif
                                    </div>
                                </div>
                                
                                <div class="hr-line-dashed"></div>
                                <div class="form-group  row">
                                    <div class="col-sm-12">
                                        <input type="submit" class="btn btn-primary" value="Update">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection